version: "3.2"

services:
  api:
    build: ./images/api
    ports:
      - 1000:3000
    volumes:
      - ./images/api/src:/usr/api/src

  front-end:
    build: ./images/front-end
    ports:
      - 1001:3000
    volumes:
      - ./images/api/src:/user/app/src

  