version: "3.2"

services:
  api:
    build: ./images/api
    ports:
      - 1000:3000
    volumes:
      - ./images/api/src:/usr/api/src
    # environment:
    #   DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      POSTGRES_HOST_AUTH_METHOD:
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  web:
    build: ./images/web
    ports:
      - 80:80
    volumes:
       - ./images/web/src/:/usr/share/nginx/html/

  