version: "3.2"

services:
  api:
    build: ./images/api
    ports:
      - 1000:3000
    volumes:
      - ./images/api/src:/usr/api/src

  store:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}


  front-end:
    build: ./images/front-end
    ports:
      - 1001:3000
    volumes:
      - ./images/api/src:/user/app/src

  